name: auto
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+3

environment:
  sdk: ">=2.17.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.3
  cupertino_icons: ^1.0.5
  syncfusion_flutter_datepicker: 20.2.43
  json_annotation: ^4.7.0
  dio: ^4.0.6
  package_info_plus: ^3.0.1
  video_player: ^2.4.10
  dotted_line: ^3.1.0
  yandex_mapkit: ^3.2.0
  rxdart: ^0.27.7
  get_it: ^7.2.0
  formz: ^0.4.1
  flutter_bloc: ^8.0.0
  flutter_svg: ^1.0.3
  keyboard_dismisser: ^2.0.1
  jiffy: ^5.0.0
  mask_text_input_formatter: ^2.3.0
  internet_connection_checker: ^1.0.0+1
  pin_code_fields: ^7.3.0
  share_plus: ^6.3.0
  connectivity_plus: ^3.0.2
  url_launcher: ^6.0.20
  image_picker: ^0.8.4+11
  cached_network_image: ^3.2.3
  photo_view: ^0.14.0
  shimmer: ^2.0.0
  geolocator: ^9.0.2
  easy_localization: ^3.0.1
  freezed_annotation: ^2.0.1
  carousel_slider: ^4.1.1
  flutter_cupertino_datetime_picker: ^3.0.0
  lottie: ^1.4.1
  linked_scroll_controller: ^0.2.0
  shared_preferences: ^2.0.15
  percent_indicator: ^4.2.2
  flutter_html: ^3.0.0-alpha.6
  visibility_detector: ^0.3.3
  flutter_rating_bar: ^4.0.1
  permission_handler: ^10.2.0
  device_info_plus: ^8.0.0
  webview_flutter: ^4.0.2
  sign_in_with_apple: ^4.3.0
  google_sign_in: ^5.4.4
  flutter_facebook_auth: ^5.0.7
  alice: ^0.3.2
  firebase_crashlytics: ^3.0.14
  map_launcher: ^2.5.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.3
  freezed: ^2.0.2
  json_serializable: ^6.5.4
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/index.html
    - assets/icons/
    - assets/icons/splash/
    - assets/icons/reviews/
    - assets/icons/global/
    - assets/images/global/
    - assets/images/
    - assets/icons/global/
    - assets/icons/profile/
    - assets/icons/navbar/
    - assets/images/car_single/
    - assets/icons/car_single/
    - assets/icons/search/
    - assets/icons/review/
    - lib/assets/strings/
    - assets/lottie/
    - assets/icons/auth/
    - assets/fonts/

  fonts:
    - family: Averta CY
      fonts:
        - asset: assets/fonts/averta_cy/AvertaCY-Black.otf
          weight: 900
        - asset: assets/fonts/averta_cy/AvertaCY-Bold.otf
          weight: 700
        # - asset: assets/fonts/averta_cy/AvertaCY-ExtraBold.otf
        #   weight: 800
        - asset: assets/fonts/averta_cy/AvertaCY-Extrathin.otf
          weight: 200
        - asset: assets/fonts/averta_cy/AvertaCY-Light.otf
          weight: 300
        - asset: assets/fonts/averta_cy/AvertaCY-Regular.otf
          weight: 400
        # - asset: assets/fonts/averta_cy/AvertaCY-SemiBold.otf
          # weight: 600
        - asset: assets/fonts/averta_cy/AvertaCY-Thin.otf
          weight: 100

