import 'package:auto/assets/colors/color.dart';
import 'package:flutter/material.dart';

//ignore_for_file: public_member_api_docs

/// Semantic aliases.
/// Replenished as needed.
/// Use only the main palette.
class LightThemeColors {
  static const displayLarge = _midnightExpress;
  static const displayMedium = _grey;
  static const displaySmall = _mediumSlateBlue;
  static const headlineMedium = _white;
  static const headlineSmall = _cinnabar;
  static const titleLarge = _grey;
  static const headline7 = _midnightExpress;
  static const bodyLarge = _solitude;
  static const bodyMedium = _dodgerBlue;
  static const titleMedium = _black;
  static const titleSmall = _blackOpacity;
  static const bodySmall = _nero;
  static const button = _cinnabar;
  static const surface = _midnightExpress;
  static const appBar = _midnightExpress;
  static const darkToWhite = _nero;
  static const darkGreyToWhite = _dolphin;
  static const dividerColorToDarkGreyOpacity = _solitude;
  static const whiteToGrey = _white;
  static const dividerColorToWhiteOpacity = _solitude;
  static const scaffoldBackground = _solitudeContainer;
  static const solitudeToBastille = _solitude;
  static const backgroundColor = _black;
  static const navBarIndicator = _mediumSlateBlue;
  static const divider = _solitude;
  static const hintColor = _ghost;
  static const appBarColor = _white;
  static const appBarActionIcon = _grey;
  static const warmerGreyToDarkGrey = _ghost;
  static const whiteToWhiteOpacity20 = _white;
  static const solitudeToGhost = _solitude;
  static const seashellToCinnabar15 = _seashell;

  static const smoky = _smoky;
  static const greyTextColor = _mischka;
  static const whiteToSmoky = _white;
  static const whiteSmokeToNightRider = _whiteSmoke;
  static const whiteToNero = _white;
  static const redToWhite = red;
  static const mediumSlateBlueToDolphin = _mediumSlateBlue;
  static const whiteSmokeToEclipse = _whiteSmoke1;
  static const solitudeToEclipse = _solitude;
  static const gainsboroToBlack = _solitude1;
  static const solitude1ToNero = _solitude1;
  static const solitude2ToNightRider = _solitude1;
  static const solitude2ToNero = _solitude3;
  static const whiteWithOpacity90ToNero = _whiteWithOpacity90ToNero;
  static const whiteSmoke2ToNightRider = _whiteSmoke2;
  static const solitudeTo1Black = _solitude1;
  static const whiteLilacToNightRider = _whiteLilac;
  static const whiteToNightRider = _white;
  static const midnightExpressToGreySuit = _midnightExpress;
  static const snowToNero1 = _snow;
  static const whiteToNero1 = _white;
  static const whiteLilacToPayneGrey = _whiteLilac;
  static const whiteToNero2 = _white;
  static const whiteToWithOpacity8 = _white;

  //for keyboard
  static const whiteToDimGray = _white;
  static const primaryColor = _cinnabar;

  static const dodgerBlueToWhite80 = _dodgerBlue;
  static const blackToWhite80 = _black;
  static const prussianBlueToWhite80 = _prussianBlue;
  static const dividerColorToGrey = _solitude;
  static const warmerGreyToDarkGray = _ghost;
  static const lightGreyToEclipse = _eclipse;
  static const solitudeToNero = _solitude3;
  static const solitudeToDarkRider = _solitude1;
  static const veryLightGreyToEclipse = _veryLightGrey;
  static const whiteToDolphin = _white;
  static const solitudeToWhite35 = _solitude;
  static const solitudeToSolitude14 = _solitude;
  static const transparentToSolitude12 = _transparent;
  static const solitudeToDarkGray95 = _solitude;
  static const mediumSlateBlueToWhite = _mediumSlateBlue;
  static const solitudeToCharcoal = _solitude;
  static const whiteToDark = _white;
  static const midnightExpressToWhite = _midnightExpress;
  static const snowToNightRider = _snow;
  static const stormGrey16ToStormGrey32 = _stormGrey16;
  static const mediumSlateBlue50ToNightRider = _mediumSlateBlue50;
  static const lavenderToMediumSlateBlue30 = _lavender;
  static const ghostWhiteToUltramarine10 = _ghostWhite;
  static const lavenderToUltramarine30 = _lavender;
  static const whiteSmokeToDark = _whiteSmoke;
  static const solitudeContainerToDark = _solitudeContainer;
  static const solitudeContainerToBlack = _solitudeContainer;
  static const solitudeContainerToNero1 = _solitudeContainer;
  static const aluminumToDolphin = _aluminum;
  static const transparentToNightRider = Colors.transparent;
  static const ghostToEclipse = _ghost;
  static const snowToNero = _snow;
  static const blackToWhite = _black;
  static const stormGrey12ToStormGrey24 = _stormGrey12;
  static const whiteToGondola = _white;
  static const midnightExpressToDolphin = _midnightExpress;
  static const whiteToWhite8 = _white;
  static const whiteToSecondNero = _white;
  static const greySuitToWhite60 = _grey;
  static const dolphinToWhite60 = _dolphin;
  static const dolphinToWhite = _dolphin;
  static const solitudeToGondola = _solitude1;
  static const solitudeToPayneGrey = _solitude;
  static const dolphinToGreySuit = _dolphin;
  static const dolphinToGhost = _dolphin;
  static const lightSlateBlue12ToLightSlateBlue = _lightSlateBlue12;
  static const whiteLilacToWhiteLilac10 = _whiteLilac;
  static const solitudeBorderToSolitudeBorder10 = _solitude1;
  static const whiteLilacToWhite4 = _whiteLilac;
  static const solitudeToDolphin8 = _solitude1;
  static const cinnabar12ToCinnabar = _cinnabar12;
  static const navBarUnselected = _white;
  static const whiteToEclipse = _white;
  static const borderGreyToDark = _solitude1;
  static const iconPearlToWhite = _spunPearl;
  static const whiteToDarkRider = _white;
  static const borderGreyToGreen = _solitude1;
  static const lightGreenToDarkGreen = _hummingBird;
  static const greyToDarkRider = _solitude1;
  static const darkToPurple = _midnightExpress;
  static const darkToGrey = _midnightExpress;
  static const solitudeToDolphinBorder = _solitude1;
  static const whiteSmoke78ToWhiteSmoke12 = _whiteSmoke78;
  static const ghostToGondola = _ghost;
  static const tangerineYellowToMediumSlateBlue = _tangerineYellow;
  static const greySuitToWhite = _grey;
  static const snowToBlack = _snow;
  static const greyToCinnabar = _grey;
  static const solitudeToNightRider = _solitude;
  static const whiteToBlack = _white;
  static const snow1ToCocoaBrown = _snow1;
  static const fairPinkToIndianTan = _fairPink;

  static const lavenderBlueToCharcoal = _lavenderBlue;
  static const ghostWhite1ToNero = _ghostWhite1;
  static const ghostToGreySuit = _ghost;
  static const silver50ToNightRider = _silver50;
  static const whiteSmokeToBlack = _whiteSmoke1;
  static const silverToNightRider = _silver;
  static const textBlue = _blueText;
  static const dividerColor = _solitude;
  static const tutuToRed = tutu;

  static const greyContainer27 = _whiteLilac1;
  static const greenContainer27 = _cosmicLatte;
  static const redContainer27 = _roseWhite;
  static const blueContainer27 = _lavender1;
  static const darkblueContainer27 = _midnight;
  static const lightGreenContainer27 = _turtleGreen;
  static const yelowOneContainer27 = _cocoaBrownThree;
  static const yelowTwoContainer27 = _cocoaBrownTwo;
  static const brownContainer27 = _indianTanTwo;
  static const hummingBirdTwo = _hummingBirdTwo;//green
  static const blanchedAlmonToCountyGreen = _blanchedAlmond;//yellow
  static const karryToBrownsOlive = _karry;//pink
  static const blueChalkToCaputMortum = _blueChalk;//fiolet
  static const sindirellaToBurrentCrinson = _sindirella;//lightred
  static const roseWhiteToEclipse = _roseeWhite;//lightred
}

// Main palette (http://www.color-blindness.com/color-name-hue/).
const _midnightExpress = Color(0xff171725);
const _nero = Color(0xff2B2B2B);
const _dolphin = Color(0xff696974);
const _solitude = Color(0xffE2E2EA);
const _solitude3 = Color(0xffFAFAFB);
const _white = Color(0xffffffff);
const _whiteWithOpacity90ToNero = Color.fromRGBO(255, 255, 255, 9);
const _ghost = Color(0xffB5B5BE);
const _whiteSmoke = Color(0xfff8f8f8);
const _whiteSmoke1 = Color(0xffF4F4F4);
const _grey = Color(0xff92929D);
const _mediumSlateBlue = Color(0xff695CEA);
const _cinnabar = Color(0xffEA5930);
const _cinnabar12 = Color(0x1fEA5930);
const _black = Color(0xff000000);
const _blackOpacity = Color(0x80000000);
const _dodgerBlue = Color(0xff007AFF);
const _veryLightGrey = Color(0xFFCCCCCC);
const _transparent = Colors.transparent;
const _prussianBlue = Color(0xff022F5E);
const _snow = Color(0xffFFFCFB);
const _mediumSlateBlue50 = Color(0x1a695cea);
const _stormGrey16 = Color(0x29787880);
const _lavender = Color(0xffF0EFFD);
const _ghostWhite = Color(0xffF7F6FF);
const _solitudeContainer = Color(0xfffafafb);
const _aluminum = Color(0xff7f878f);
const _stormGrey12 = Color(0x1f767680);
const _lightSlateBlue12 = Color(0x1f7B61FF);
const _whiteLilac = Color(0xffF4F4F5);
const _solitude1 = Color(0xFFF1F1F5);
const _spunPearl = Color(0xFF9E9EA9);
const _hummingBird = Color(0xffF0FAF6);
const _eclipse = Color(0xff373737);
const _whiteSmoke2 = Color(0xfff4f4f4);
const _whiteSmoke78 = Color(0xc7e9e9e9);
const _tangerineYellow = Color(0xffFFC908);
const _snow1 = Color(0xfffff7f5);
const _lavenderBlue = Color(0xffE2DFFF);
const _ghostWhite1 = Color(0xffF2F1FF);
const _silver50 = Color(0x80B6B6B6);
const _silver = Color(0xffc4c4c4);
const _blueText = Color(0xff4D88C8);
const _seashell = Color(0xffFFF8F5);
const _smoky = Color(0xff5D5D67);
const _mischka = Color(0xffA5AAB4);
const _fairPink = Color(0xffF3E1DD);
const _whiteLilac1 = Color(0xFFF7F7F8);
const _cosmicLatte = Color(0xFFF0FAF6);
const _roseWhite = Color(0xFFFDF4F3);
const _lavender1 = Color(0xFFF2F4FC);
const _cocoaBrownThree = Color(0xFFFFF6E1);
const _cocoaBrownTwo = Color(0xFFFFF6E1);
const _midnight = Color(0xFF171725);
const _indianTanTwo = Color(0xffEA5930);
const _turtleGreen = Color(0xff55BB00);
const _hummingBirdTwo = Color(0xffDEF4F8);//green
const _blanchedAlmond = Color(0xffFFF0CD);//yellow
const _karry = Color(0xffFED7CC);//pink
const _blueChalk = Color(0xffD6D3E6);//fiolet
const _sindirella = Color(0xffFAD9D0);//lightred
const _roseeWhite = Color(0xffFEF8F7);//lightred
// const _snowyMint = Color(0xffDCF1CA);//green




