// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIet-sOi2fBDtBGOwZAudv1XtiR8Y1hBI',
    appId: '1:75079193779:web:4bf55d53d988ffbad2ccc6',
    messagingSenderId: '75079193779',
    projectId: 'auto-c617f',
    authDomain: 'auto-c617f.firebaseapp.com',
    storageBucket: 'auto-c617f.appspot.com',
    measurementId: 'G-68QEVBQ50X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOc_J6eumlkG-o4_VMpsqlGKT3VKPWLJI',
    appId: '1:75079193779:android:db913c7358fe47abd2ccc6',
    messagingSenderId: '75079193779',
    projectId: 'auto-c617f',
    storageBucket: 'auto-c617f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvMl2hOkVR5NkspcCYYN1wP7Bu4-Bpo0Y',
    appId: '1:75079193779:ios:0077effeed2bb5fdd2ccc6',
    messagingSenderId: '75079193779',
    projectId: 'auto-c617f',
    storageBucket: 'auto-c617f.appspot.com',
    iosClientId: '75079193779-hp3jlq6evh11rn98vbgeb9vdfcecudon.apps.googleusercontent.com',
    iosBundleId: 'org.uicgroup.auto.uz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvMl2hOkVR5NkspcCYYN1wP7Bu4-Bpo0Y',
    appId: '1:75079193779:ios:10260d871f2f0889d2ccc6',
    messagingSenderId: '75079193779',
    projectId: 'auto-c617f',
    storageBucket: 'auto-c617f.appspot.com',
    iosClientId: '75079193779-6pak24r73pipl4hogov2ajuu2m8t1rq8.apps.googleusercontent.com',
    iosBundleId: 'org.uicgroup.auto.autoUzMobile',
  );
}
