// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtRt3RZ-TbdQwWjudRxvokTYGELxjKqUA',
    appId: '1:742569060269:web:de9994264ebda590f2e324',
    messagingSenderId: '742569060269',
    projectId: 'avto-a6713',
    authDomain: 'avto-a6713.firebaseapp.com',
    storageBucket: 'avto-a6713.appspot.com',
    measurementId: 'G-SD0T2XY2EG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0YtwYM4_atzbqVqDN6IyrNeln3l3uAxE',
    appId: '1:742569060269:android:a97b03acf7d7ebd2f2e324',
    messagingSenderId: '742569060269',
    projectId: 'avto-a6713',
    storageBucket: 'avto-a6713.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhBDfyBI3ihG6b2h2XWaNQ0oTv74ekfO8',
    appId: '1:742569060269:ios:ae41c0f863da58a3f2e324',
    messagingSenderId: '742569060269',
    projectId: 'avto-a6713',
    storageBucket: 'avto-a6713.appspot.com',
    iosClientId: '742569060269-t14ostif5cd9mjp5rqtrso9jd17p116c.apps.googleusercontent.com',
    iosBundleId: 'org.uicgroup.avto.uz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhBDfyBI3ihG6b2h2XWaNQ0oTv74ekfO8',
    appId: '1:742569060269:ios:2d680dee0ca712e2f2e324',
    messagingSenderId: '742569060269',
    projectId: 'avto-a6713',
    storageBucket: 'avto-a6713.appspot.com',
    iosClientId: '742569060269-ib04vrabgsrk9ejjv510b71f4m495d7s.apps.googleusercontent.com',
    iosBundleId: 'org.uicgroup.auto.autoUzMobile',
  );
}
