class CarSingleEntity {
  final String autoName;
  final String price;
  final String date;
  final String views;
  final int id;
  final String issueYear;
  final String milleage;
  final String body;
  final String color;
  final String complectation;
  final String engineSize;
  final String transmission;
  final String rastomojka;
  final String sellerName;
  final String accident;
  final String sellerComent;
  final String driverAirbag;
  final String passengerAirabag;
  final String windowAirbag;
  final String legsAirbag;
  final String hsa;
  final String ptsOwner;
  final String zalog;
  final String wanted;
  final String milleageHistory;
  final String leftFrontDoor;
  final String leftDoor;
  final String rightFrontDoor;
  final String rightDoor;
  final int transmissionCount;
  final String engineSizeM;
  final String driveUnit;
  final String engineType;
  final String clearance;
  final String speed;
  final String enginePower;
  final String weight;
  final String fuelConsuption;
  final String transmissionType;
  final String bodytype;
  final String similarPrice;

  const CarSingleEntity({
    this.autoName = '',
    this.price = '',
    this.date = '',
    this.views = '',
    this.id = 0,
    this.issueYear = '',
    this.milleage = '',
    this.body = '',
    this.color = '',
    this.complectation = '',
    this.engineSize = '',
    this.transmission = '',
    this.rastomojka = '',
    this.sellerName = '',
    this.accident = '',
    this.sellerComent = '',
    this.driverAirbag = '',
    this.passengerAirabag = '',
    this.windowAirbag = '',
    this.legsAirbag = '',
    this.hsa = '',
    this.ptsOwner = '',
    this.zalog = '',
    this.wanted = '',
    this.milleageHistory = '',
    this.leftFrontDoor = '',
    this.leftDoor = '',
    this.rightFrontDoor = '',
    this.rightDoor = '',
    this.transmissionCount = 0,
    this.engineSizeM = '',
    this.driveUnit = '',
    this.engineType = '',
    this.clearance = '',
    this.speed = '',
    this.enginePower = '',
    this.weight = '',
    this.fuelConsuption = '',
    this.transmissionType = '',
    this.bodytype = '',
    this.similarPrice = '',
  });
}
